[project]
name = "lynx-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "John O'Meara", email = "johnomeara40@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "awscli>=1.46.1",
    "beautifulsoup4>=4.15.0",
    "h5py>=3.16.0",
    "pandas>=3.0.5",
    "pybigwig>=0.3.25",
    "pyfaidx>=0.9.0.4",
    "requests>=2.34.2",
    "tqdm>=4.70.0",
]

[tool.uv]
package = false
